"""File-grant filtering and syntax-preserving candidate storage; no code execution."""

import gzip
import hashlib
import json
import shutil
from types import SimpleNamespace

import pytest

from minifrontier.data.code_sources import CODE_SOURCE, code_rows, licensed_record
from minifrontier.data.corpus import CorpusBuilder

APACHE = """# Copyright 2020 Example authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
"""


def row(text=None):
    return dict(
        content=text or APACHE + '\ndef value():\n    return "\uff21  B"\n',
        repo_name="example/library",
        path="library/value.py",
        license="apache-2.0",
        autogenerated=False,
    )


def test_code_requires_matching_file_grant_including_spdx_and_python_syntax():
    record, reason = licensed_record(row(), "shard:line1")
    assert reason is None and record["text"] == row()["content"]
    assert record["license"] == "Apache-2.0" and record["repo_id"] == "example/library"
    assert record["source_metadata"]["original_repository_commit"] is None
    assert record["raw_text_sha256"] == hashlib.sha256(record["text"].encode()).hexdigest()
    assert licensed_record(dict(row(), license="mit"), "row")[1] == "no_matching_in_file_license"
    assert (
        licensed_record(row("# SPDX-License-Identifier: GPL-3.0-only\n" + row()["content"]), "row")[
            1
        ]
        == "conflicting_spdx_header"
    )
    assert (
        licensed_record(row("def value():\n    return 7\n" + APACHE), "row")[1]
        == "missing_or_conflicting_file_grant"
    )
    assert (
        licensed_record(row(APACHE + "def value(:\n    return 7\n"), "row")[1]
        == "not_parseable_python3"
    )
    assert (
        licensed_record(dict(row(), path="vendor/value.py"), "row")[1]
        == "generated_or_vendored_path"
    )
    assert licensed_record(dict(row(), path="../value.py"), "row")[1] == "missing_or_invalid_origin"


def test_code_bytes_unicode_indentation_and_string_spaces_survive_corpus(tmp_path, monkeypatch):
    monkeypatch.setattr(shutil, "disk_usage", lambda _: SimpleNamespace(free=900 * 1024**3))
    builder = CorpusBuilder(tmp_path / "corpus")
    sources = [row()["content"], row()["content"].replace("\uff21  B", "A B")]
    for index, source in enumerate(sources):
        record, reason = licensed_record(row(source), f"row:{index}")
        assert reason is None and builder.add(record)
    repeated, _ = licensed_record(dict(row(), repo_name="example/fork"), "duplicate")
    assert not builder.add(repeated)
    assert builder.counts["accepted"] == 2 and builder.counts["exact_duplicates"] == 1
    stored = {text for (text,) in builder.db.execute("SELECT text FROM samples")}
    assert stored == set(sources)
    builder.finalize()
    assert len({group for (group,) in builder.db.execute("SELECT group_root FROM samples")}) == 1
    builder.db.close()


@pytest.mark.parametrize("corrupt", [False, True])
def test_code_download_checks_fixed_hash_and_closes_its_only_shard(tmp_path, monkeypatch, corrupt):
    import huggingface_hub
    import requests

    monkeypatch.setattr(shutil, "disk_usage", lambda _: SimpleNamespace(free=900 * 1024**3))
    content = gzip.compress((json.dumps(row()) + "\n" + json.dumps(row()) + "\n").encode())
    file = SimpleNamespace(
        rfilename="file-1.json.gz",
        size=len(content),
        lfs=SimpleNamespace(sha256="0" * 64 if corrupt else hashlib.sha256(content).hexdigest()),
    )
    monkeypatch.setattr(
        huggingface_hub,
        "HfApi",
        lambda token: SimpleNamespace(
            dataset_info=lambda *args, **kwargs: SimpleNamespace(
                sha=CODE_SOURCE["revision"], gated=False, siblings=[file]
            )
        ),
    )

    class Response:
        def __enter__(self):
            return self

        def __exit__(self, *args):
            pass

        def raise_for_status(self):
            pass

        def iter_content(self, _size):
            yield content

    monkeypatch.setattr(requests.Session, "get", lambda *args, **kwargs: Response())
    audit = {}
    reader = code_rows(root=tmp_path, seed=42, audit=audit)
    if corrupt:
        with pytest.raises(ValueError, match="hash/size"):
            next(reader)
    else:
        item, identity = next(reader)
        assert item == row() and identity == "file-1.json.gz:line1"
        assert (tmp_path / ".code-source.json.gz").exists()
        assert audit["downloaded_bytes"] == len(content)
    reader.close()
    assert not (tmp_path / ".code-source.json.gz").exists()
