"""Public Python candidates with in-file license evidence; never execute source code."""

import ast
import gzip
import hashlib
import json
import random
import re
from pathlib import Path, PurePosixPath
from typing import Any

from minifrontier.storage import GIB, reserve_write

CODE_SOURCE: dict[str, Any] = dict(
    repo="codeparrot/codeparrot-clean-train",
    revision="3e6ab65f2864931e041f6a82db9b5a6ec2b71ab4",
    format="json_gz",
    license="per-file Apache-2.0/MIT/BSD grant must agree with the source license column",
    task="code",
    lang="code",
    max_download_bytes=3 * GIB,
    max_source_rows=500_000,
)


def licensed_record(row, identity):
    text, repo, path, declared = (row.get(k) for k in ("content", "repo_name", "path", "license"))
    if (
        not isinstance(text, str)
        or not isinstance(repo, str)
        or not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repo)
        or not isinstance(path, str)
        or PurePosixPath(path).is_absolute()
        or ".." in PurePosixPath(path).parts
        or not path.endswith(".py")
    ):
        return None, "missing_or_invalid_origin"
    if not isinstance(declared, str) or declared not in {
        "apache-2.0",
        "mit",
        "bsd-2-clause",
        "bsd-3-clause",
    }:
        return None, "unsupported_declared_license"
    if row.get("autogenerated") is not False or any(
        part.lower()
        in {
            "vendor",
            "vendored",
            "third_party",
            "third-party",
            "external",
            "externals",
            "site-packages",
            ".venv",
            "build",
        }
        for part in PurePosixPath(path).parts
    ):
        return None, "generated_or_vendored_path"
    if not 100 <= len(text) <= 100_000 or "\ufffd" in text or "\x00" in text:
        return None, "invalid_length_or_encoding"
    if any(name in path.casefold() for name in ("humaneval", "human_eval", "mbpp")):
        return None, "benchmark_path"
    try:
        tree = ast.parse(text)
    except (SyntaxError, ValueError, RecursionError):
        return None, "not_parseable_python3"
    if not tree.body or not any(
        isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) for n in ast.walk(tree)
    ):
        return None, "no_function_or_class"
    first = tree.body[0]
    header_end = first.lineno - 1
    if (
        isinstance(first, ast.Expr)
        and isinstance(first.value, ast.Constant)
        and isinstance(first.value.value, str)
    ):
        header_end = first.end_lineno or first.lineno
    header = "\n".join(text.splitlines()[: min(header_end or 0, 120)])[:16_384]
    legal = re.sub(r"[\s#*]+", " ", header).casefold()
    identifiers = re.findall(r"spdx-license-identifier\s*:\s*([^\r\n]+)", header, re.I)
    if any(value.strip(" #*/\t").casefold() != declared for value in identifiers):
        return None, "conflicting_spdx_header"
    if "copyright" not in legal or re.search(
        r"gnu (?:affero |lesser )?general public|non.?commercial|all use.*prohibited", legal
    ):
        return None, "missing_or_conflicting_file_grant"
    if declared == "apache-2.0":
        granted = all(
            s in legal
            for s in (
                "licensed under the apache license, version 2.0",
                "apache.org/licenses/license-2.0",
                "except in compliance with the license",
            )
        )
        spdx = "Apache-2.0"
    elif declared == "mit":
        granted = all(
            s in legal
            for s in (
                "permission is hereby granted, free of charge",
                "deal in the software without restriction",
                "the above copyright notice",
                "permission notice shall be included",
                "software is provided",
                "as is",
            )
        )
        spdx = "MIT"
    else:
        granted = all(
            s in legal
            for s in (
                "redistribution and use in source and binary forms",
                "redistributions of source code",
                "redistributions in binary form",
                "this software is provided",
                "as is",
            )
        )
        endorsement = "neither the name" in legal or bool(
            re.search(r"name.*may.*(?:endorse|promote)", legal)
        )
        granted = granted and (endorsement == (declared == "bsd-3-clause"))
        spdx = "BSD-3-Clause" if endorsement else "BSD-2-Clause"
    if not granted:
        return None, "no_matching_in_file_license"
    raw = text.encode("utf-8")
    syntax = hashlib.sha256(ast.dump(tree, include_attributes=False).encode()).hexdigest()
    return dict(
        source=CODE_SOURCE["repo"],
        revision=CODE_SOURCE["revision"],
        item_id=identity,
        group_id=repo.casefold(),
        repo_id=repo.casefold(),
        license=spdx,
        lang="code",
        task="code",
        stage="pretrain",
        text=text,
        text_format="source_code",
        syntax_sha256=syntax,
        raw_text_sha256=hashlib.sha256(raw).hexdigest(),
        source_metadata=dict(
            repo_name=repo,
            path=path,
            declared_license=declared,
            license_evidence="matching grant in comments or initial module docstring",
            license_header_sha256=hashlib.sha256(header.encode()).hexdigest(),
            computed_git_blob_sha1=hashlib.sha1(
                b"blob " + str(len(raw)).encode() + b"\0" + raw
            ).hexdigest(),
            original_repository_commit=None,
            original_commit_status="not provided by source; dataset revision and content hashes bind this extracted file",
        ),
        quality_flags=[
            "candidate-not-formally-admitted",
            "python3-parsed-not-executed",
            "benchmark-content-review-pending",
        ],
    ), None


def code_rows(*, root, seed, audit, resume=False):
    """Shuffle pinned shards; validate one bounded gzip before streaming its JSON lines."""
    import requests
    from huggingface_hub import HfApi

    source = CODE_SOURCE
    info = HfApi(token=False).dataset_info(
        source["repo"], revision=source["revision"], files_metadata=True
    )
    if info.sha != source["revision"] or info.gated:
        raise ValueError("public code source revision/access contract changed")
    files = sorted(
        (f for f in info.siblings or [] if f.rfilename.endswith(".json.gz")),
        key=lambda f: f.rfilename,
    )
    if not files:
        raise ValueError("pinned code source contains no gzip shards")
    random.Random(seed).shuffle(files)
    skip = audit.get("completed_read_rows", audit.get("read_rows", 0)) if resume else 0
    visited = 0
    if not resume:
        audit.update(files={}, read_rows=0, downloaded_bytes=0)
    audit["sampling"] = "seeded shard permutation; stream all selected shard rows in original order"
    audit["completed_read_rows"] = skip
    audit.setdefault("reader_rejections", {})
    cache = Path(root) / ".code-source.json.gz"
    try:
        with requests.Session() as session:
            for file in files:
                if not file.lfs or not file.size or not 0 < file.size <= 300 * 1024**2:
                    raise ValueError("code shard lacks a hash or exceeds the 300 MiB bound")
                if audit["downloaded_bytes"] + file.size > source["max_download_bytes"]:
                    audit["read_limit"] = "network_byte_budget"
                    return
                url = f"https://huggingface.co/datasets/{source['repo']}/resolve/{source['revision']}/{file.rfilename}"
                digest, size = hashlib.sha256(), 0
                with reserve_write(cache, file.size, reserve_bytes=80 * GIB):
                    with (
                        session.get(url, stream=True, timeout=(30, 90)) as response,
                        cache.open("wb") as handle,
                    ):
                        response.raise_for_status()
                        for chunk in response.iter_content(1024**2):
                            size += len(chunk)
                            audit["downloaded_bytes"] += len(chunk)
                            if size > file.size:
                                raise ValueError("code download exceeds pinned shard size")
                            digest.update(chunk)
                            handle.write(chunk)
                    if size != file.size or digest.hexdigest() != file.lfs.sha256:
                        raise ValueError("code source shard hash/size mismatch")
                audit["files"][file.rfilename] = dict(size=size, sha256=digest.hexdigest())
                decompressed = 0
                with gzip.open(cache, "rb") as stream:
                    for number in range(1, source["max_source_rows"] + 1):
                        line = stream.readline(2 * 1024**2 + 1)
                        if not line:
                            break
                        decompressed += len(line)
                        oversized = len(line) > 2 * 1024**2
                        while oversized and not line.endswith(b"\n") and decompressed <= 2 * GIB:
                            line = stream.readline(2 * 1024**2)
                            decompressed += len(line)
                            if not line:
                                break
                        if decompressed > 2 * GIB:
                            audit["files"][file.rfilename]["decompression_limit_at_line"] = number
                            break
                        visited += 1
                        if visited <= skip:
                            continue
                        if audit["read_rows"] >= source["max_source_rows"]:
                            audit["read_limit"] = "source_row_budget"
                            return
                        audit["read_rows"] += 1
                        if oversized:
                            audit["reader_rejections"]["oversized_json_record"] = (
                                audit["reader_rejections"].get("oversized_json_record", 0) + 1
                            )
                        else:
                            yield json.loads(line), f"{file.rfilename}:line{number}"
                        # The generator resumes only after the caller handled this row.
                        audit["completed_read_rows"] = audit["read_rows"]
                cache.unlink()
    finally:
        cache.unlink(missing_ok=True)
