"""Regenerate native vision primitives from the strategy's pinned snapshots.

Adapters remove Transformers registration and hardware-only wrappers. All source
matrices, normalization, patch ordering, positional and merger math are retained.
"""

import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def extract(path, names):
    source = path.read_text()
    lines = source.splitlines(keepends=True)
    return "\n\n".join(
        "".join(lines[node.lineno - 1 : node.end_lineno])
        for node in ast.parse(source).body
        if isinstance(node, (ast.ClassDef, ast.FunctionDef)) and node.name in names
    )


def write(family, body, preamble, license_path, filename="upstream_vision.py"):
    license_text = "\n".join("# " + line for line in license_path.read_text().splitlines())
    target = ROOT / "minifrontier/models" / family / filename
    target.write_text(
        "# Generated by scripts/extract_vision_sources.py; see source snapshot hashes.\n"
        "# mypy: ignore-errors\n# ruff: noqa\n"
        + license_text
        + "\n"
        + preamble
        + "\n"
        + body
        + "\n"
    )


def main():
    source_root = ROOT / "third_party/upstream"
    base = source_root / "kimi-k3-c5d1dd4"
    body = extract(
        base / "modeling_kimi_k3.py",
        {
            "eager_attention",
            "_apply_rope_input_validation",
            "get_rope_shape",
            "apply_rope",
            "get_1d_sincos_pos_embed_from_grid",
            "get_1d_sincos_pos_embed",
            "Learnable2DInterpPosEmbDivided_fixed",
            "MoonVision3dPatchEmbed",
            "Rope2DPosEmbRepeated",
            "MLP2",
            "MoonViTEncoderLayer",
            "MoonViT3dEncoder",
            "tpool_patch_merger",
            "PatchMergerMLPV2",
        },
    )
    # Omit the compilation/cache decorators on get_rope_shape; math unchanged.
    write(
        "minikimik3",
        body,
        """
from __future__ import annotations
import math
from collections.abc import Sequence
from typing import Optional
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F

def segmented_sdpa(q, k, v, q_cu_seqlens=None, k_cu_seqlens=None, **kwargs):
    pieces = []
    for start, end in zip(q_cu_seqlens[:-1].tolist(), q_cu_seqlens[1:].tolist()):
        out = F.scaled_dot_product_attention(q[start:end].transpose(0,1),
                                             k[start:end].transpose(0,1),
                                             v[start:end].transpose(0,1), dropout_p=0.0)
        pieces.append(out.transpose(0,1).flatten(-2))
    return torch.cat(pieces)

VL_VISION_ATTENTION_FUNCTIONS = {"sdpa": segmented_sdpa}
""",
        base / "LICENSE",
    )
    write(
        "minikimik3",
        (base / "media_utils.py").read_text(),
        "",
        base / "LICENSE",
        "upstream_processing.py",
    )
    # Bind the source eager implementation after its definition for oracle comparisons.
    path = ROOT / "minifrontier/models/minikimik3/upstream_vision.py"
    path.write_text(
        path.read_text() + '\nVL_VISION_ATTENTION_FUNCTIONS["eager"] = eager_attention\n'
    )

    base = source_root / "qwen4_exp-4177486"
    body = extract(
        base / "modeling_qwen4_exp.py",
        {
            "Qwen4ExpVisionRotaryEmbedding",
            "Qwen4ExpVisionMLP",
            "Qwen4ExpVisionPatchEmbed",
            "Qwen4ExpVisionPatchMerger",
            "apply_rotary_pos_emb_vision",
            "Qwen4ExpVisionAttention",
            "Qwen4ExpVisionBlock",
        },
    )
    # Decorator bodies inside a class remain; no-op documentation/version decorators only.
    body += "\n" + extract(
        base / "vision_utils.py",
        {
            "get_vision_cu_seqlens",
            "get_vision_position_ids",
            "_interpolation_axis_taps_weights",
            "get_vision_interpolation_indices_and_weights",
        },
    )
    write(
        "miniqwen4",
        body,
        """
from __future__ import annotations
from typing import Callable, Any
import torch
from torch import nn
import torch.nn.functional as F
from .upstream_decoder import rotate_half, eager_attention_forward
Qwen4ExpVisionConfig = Any
GradientCheckpointingLayer = nn.Module
maybe_autocast = torch.autocast
ACT2FN = {"gelu_pytorch_tanh": lambda x: F.gelu(x, approximate="tanh")}
def auto_docstring(fn): return fn
def deprecate_kwarg(*args, **kwargs): return lambda fn: fn
def is_flash_attention_requested(config): return False
def get_max_seqlen(cu, config, kwargs): return int((cu[1:]-cu[:-1]).max())
def sdpa_attention(module, q, k, v, attention_mask=None, scaling=None, **kwargs):
    out = F.scaled_dot_product_attention(q, k, v, attn_mask=attention_mask, scale=scaling, dropout_p=0.0)
    return out.transpose(1,2), None
class Interfaces:
    def get_interface(self, name, default):
        return sdpa_attention if name == "sdpa" else default
ALL_ATTENTION_FUNCTIONS = Interfaces()
""",
        base / "LICENSE",
    )

    write(
        "miniqwen4",
        extract(base / "image_processing_qwen2_vl.py", {"smart_resize"}),
        "import math",
        base / "LICENSE",
        "upstream_processing.py",
    )

    base = source_root / "deepseek-v4-vision-6821d6a"
    body = (base / "inference/vision.py").read_text()
    # Original launcher uses CUDA default_device. Our adapter passes the actual device.
    body = body.replace(
        "        for block in self.blocks:",
        "        cos, sin = cos.to(x.device), sin.to(x.device)\n        for block in self.blocks:",
    )
    write("minideepseekv4", body, "", base / "LICENSE")
    write(
        "minideepseekv4",
        (base / "inference/image_processor.py").read_text(),
        "",
        base / "LICENSE",
        "upstream_processing.py",
    )
    write(
        "minideepseekv4",
        extract(base / "inference/model.py", {"get_image_visible", "get_window_topk_idxs_visible"})
        .replace(
            "torch.arange(seqlen, dtype=torch.int32)",
            "torch.arange(seqlen, dtype=torch.int32, device=input_ids.device)",
        )
        .replace(
            "torch.arange(seqlen).unsqueeze(0)",
            "torch.arange(seqlen, device=left.device).unsqueeze(0)",
        )
        .replace("torch.arange(width)", "torch.arange(width, device=left.device)"),
        "import torch\nfrom .upstream_processing import IMAGE_START, IMAGE_END",
        base / "LICENSE",
        "upstream_visibility.py",
    )


if __name__ == "__main__":
    main()
